// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1615278803);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1615278923);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1615278563);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1615278683);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1615279043);
user_pref("browser.cache.disk.capacity", 972800);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "ZA");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Thu, 25 Feb 2021 01:53:01 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1615278819);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"207d97f2-2a90-4f4e-99a1-d0cf2f88b206\",\"default-theme@mozilla.org\":\"02056b71-2709-4f08-941a-a9c37e5c9506\",\"google@search.mozilla.org\":\"b83cb76f-c9d7-4ef1-90b7-d426bf0f0b60\",\"amazondotcom@search.mozilla.org\":\"a2766c71-b960-4466-9008-155baa5e2c7b\",\"bing@search.mozilla.org\":\"65f8b12f-b286-4379-a57e-aadc11dfb96b\",\"ddg@search.mozilla.org\":\"acf3e038-6030-493d-ba18-7ee780bd62e6\",\"twitter@search.mozilla.org\":\"fe6d2444-f2bc-485d-bcd2-d561548855a7\",\"wikipedia@search.mozilla.org\":\"e87f07fe-76a5-429e-b322-0d8fc0a612d5\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "ed96a6e0-578a-4d98-a744-0ebe3295d0b");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("security.sandbox.plugin.tempDirSuffix", "f9e97872-d0da-4b9d-8a9a-2a11a38caa6f");
user_pref("services.blocklist.pinning.checked", 1615278703);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1615276663391\"");
user_pref("services.settings.last_update_seconds", 1615278703);
user_pref("services.settings.main.hijack-blocklists.last_check", 1615278703);
user_pref("services.settings.main.language-dictionaries.last_check", 1615278703);
user_pref("services.settings.main.sites-classification.last_check", 1615278703);
user_pref("services.settings.security.onecrl.checked", 1615278703);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "feed2614-584f-4dad-99b2-f8a0205de76d");
user_pref("toolkit.telemetry.prompted", 2);
